-- Types

local SOUND_KIND = {
	NONE = "none",
	FOLEY = "foley",
	GRASS = "grass"
}

local GEAR_SOUND_KIND = {
	MELEE = "melee",
	LIGHT = "weapon_light",
	MEDIUM = "weapon_medium",
	HEAVY = "weapon_heavy"
}

local MATERIAL_MAP = {
	["wood"] = SOUND_KIND.NONE,
	["earth"] = SOUND_KIND.GRASS,
	["bush"] = SOUND_KIND.GRASS,
	["dirt"] = SOUND_KIND.NONE,
	["metal"] = SOUND_KIND.NONE,
	["water"] = SOUND_KIND.NONE,
	["tin"] = SOUND_KIND.NONE,
	["grass"] = SOUND_KIND.GRASS,
	["gravel"] = SOUND_KIND.NONE,
	["asphalt"] = SOUND_KIND.NONE,
	["tile"] = SOUND_KIND.NONE,
	["concrete"] = SOUND_KIND.NONE,
	["shifer"] = SOUND_KIND.NONE,
	["default"] = SOUND_KIND.NONE
}

local GEAR_MAP = {
	["w_melee"] = GEAR_SOUND_KIND.MELEE,
	["w_pistol"] = GEAR_SOUND_KIND.LIGHT,
	["w_shotgun"] = GEAR_SOUND_KIND.MEDIUM,
	["w_smg"] = GEAR_SOUND_KIND.MEDIUM,
	["w_rifle"] = GEAR_SOUND_KIND.MEDIUM,
	["w_sniper"] = GEAR_SOUND_KIND.HEAVY,
	["w_explosive"] = GEAR_SOUND_KIND.MELEE,
	["w_misc"] = GEAR_SOUND_KIND.LIGHT,
	["w_base"] = GEAR_SOUND_KIND.LIGHT,
	["i_device"] = GEAR_SOUND_KIND.LIGHT
}

-- Config

local config = {
	movement_volume = 0.3,
	movement_volume_jitter = 0.1,
	movement_pitch_jitter = 0.1,

	movement_crouching_volume_coeff = 0.8,
	movement_crouching_pitch_coeff = 0.75,
	movement_sprinting_volume_coeff = 1.5,
	movement_sprinting_pitch_coeff = 1.3,

	movement_gear_sound_chance = 1.0,
	movement_gear_volume_coeff = 1.0,
	movement_gear_sprinting_volume_coeff = 1.5,

	max_movement_sound_refs = 12,
	sound_cooldown = 0 -- Actor sound stepping already paces playback.
}

-- State

local sound_refs = {}
local sound_ref_index = 0

local sound_index_by_kind = {}

local num_sounds_by_kind = {
	[SOUND_KIND.FOLEY] = 27,
	[SOUND_KIND.GRASS] = 15,
	[GEAR_SOUND_KIND.MELEE] = 6,
	[GEAR_SOUND_KIND.LIGHT] = 6,
	[GEAR_SOUND_KIND.MEDIUM] = 6,
	[GEAR_SOUND_KIND.HEAVY] = 6
}

local last_step_sound = 0

-- Ticking

function tick_sound_index(kind)
	local current_index = sound_index_by_kind[kind] or 0

	if not num_sounds_by_kind[kind] then
		return 1
	end

	local num_sounds = num_sounds_by_kind[kind]
	sound_index_by_kind[kind] = current_index % num_sounds + 1

	return sound_index_by_kind[kind]
end

function random_sound_index(kind)
	if not num_sounds_by_kind[kind] then
		return 1
	end

	return math.random(1, num_sounds_by_kind[kind])
end

function has_sound_for_material(material)
	return num_sounds_by_kind[material] ~= nil
end

function has_sound_for_gear(kind)
	return num_sounds_by_kind[kind] ~= nil
end

-- Cycle

function on_movement(material_id, power, hud_view, flags)
	if time_global() < last_step_sound + config.sound_cooldown then
		log("Skipping natural movement sound, cooldown not elapsed, " .. (
			config.sound_cooldown - (time_global() - last_step_sound)
		) .. "ms remaining.")
		return
	end

	-- Foley Sound

	local foley_sound_index = tick_sound_index(SOUND_KIND.FOLEY)
	log("Playing foley sound, index " .. foley_sound_index .. ".")
	play_step_sound(actor, SOUND_KIND.FOLEY, foley_sound_index)

	-- Gear Sound

	if math.random() < config.movement_gear_sound_chance then
		local gear_sound_kind = sound_kind_for_active_gear()

		if gear_sound_kind ~= nil and has_sound_for_gear(gear_sound_kind) then
			local gear_sound_index = tick_sound_index(gear_sound_kind)

			log("Playing gear sound for kind '" .. gear_sound_kind .. "', index " .. gear_sound_index .. ".")
			play_gear_sound(actor, gear_sound_kind, gear_sound_index)
		else
			log("No gear sound for kind '" .. (gear_sound_kind or "(None)") .. "'.")
		end
	end

	-- Material Sound

	local material = sound_material_from_id(material_id)

	if material == SOUND_KIND.NONE or not has_sound_for_material(material) then
		log("No natural movement sound for material '" .. (material or "(None)") .. "' (id '" .. material_id .. "').")
		return
	end

	local material_sound_index = tick_sound_index(material)
	play_step_sound(actor, material, material_sound_index)

	log("Playing natural movement sound for material '" ..
		material .. "' (id '" .. material_id .. "'), index " .. material_sound_index .. ".")
end

-- Data

function sound_material_from_id(material_id)
	for key, value in pairs(MATERIAL_MAP) do
		if string.find(material_id, key) then
			return value
		end
	end

	return SOUND_KIND.NONE
end

function sound_kind_for_active_gear()
	local kind = active_actor_gear_kind()

	if kind == nil then
		return nil
	end

	return GEAR_MAP[kind]
end

function active_actor_gear_kind()
	local item = db.actor:active_item()

	if item == nil then
		return nil
	end

	local item_sec = item:section();
	local kind = SYS_GetParam(0, item_sec, "kind", "")

	return kind
end

-- Actor State

function actor_is_crouching()
	return IsMoveState("mcCrouch")
end

function actor_is_sprinting()
	return IsMoveState("mcSprint")
end

-- Sound Playback

function play_step_sound(actor, kind, index)
	local sound_path = "material\\actor\\step\\" .. kind .. "_a_" .. index
	local volume = sound_volume()

	play_sound(actor, sound_path, volume)

	last_step_sound = time_global()
end

function play_gear_sound(actor, kind, index)
	local sound_path = "material\\actor\\gear\\" .. kind .. "_" .. index
	local volume = sound_volume() * config.movement_gear_volume_coeff

	if actor_is_sprinting() then
		volume = volume * config.movement_gear_sprinting_volume_coeff
	end

	play_sound(actor, sound_path, volume)
end

function play_sound(actor, sound_path, volume)
	local sound_ref = get_sound_ref(sound_path)
	sound_ref:play(actor, 0, sound_object.s2d)

	sound_ref.volume = volume
	sound_ref.frequency = sound_frequency()
end

function sound_volume()
	local jitter = random_float(-config.movement_volume_jitter, config.movement_volume_jitter)
	local volume = config.movement_volume + jitter

	if actor_is_crouching() then
		volume = volume * config.movement_crouching_volume_coeff
	elseif actor_is_sprinting() then
		volume = volume * config.movement_sprinting_volume_coeff
	end

	return volume
end

function sound_frequency()
	local jitter = 1 + random_float(-config.movement_pitch_jitter, config.movement_pitch_jitter)

	if actor_is_sprinting() then
		jitter = jitter * config.movement_sprinting_pitch_coeff
	elseif actor_is_crouching() then
		jitter = jitter * config.movement_crouching_pitch_coeff
	end

	return jitter
end

function get_sound_ref(sound_file)
	sound_ref_index = (sound_ref_index + 1) % config.max_movement_sound_refs
	sound_refs[sound_ref_index] = sound_object(sound_file)

	return sound_refs[sound_ref_index]
end

-- Utility

function log(message)
	-- printf("SNMS: " .. message)
end

-- Hooks

function on_game_start()
	RegisterScriptCallback("actor_on_footstep", on_movement)
end
